Fix dummy_fail test vector
Apparently, having 'fail' in the test name has the following
result:

Traceback (most recent call last):
  File "/home/pablo/Fluendo/fluster/fluster/test.py", line 73, in _test
    self.assertEqual(self.test_vector.result.lower(), result.lower(),
  File "/usr/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.8/unittest/case.py", line 1292, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: _test() takes 1 positional argument but 2 were given

Most likely this is due to some hidden witchcraft thingy done on
Python's unit test framework. We set the test name by doing:

        setattr(self, test_vector.name, self._test)
        super().__init__(test_vector.name)