Fix parse argument error with Python 3.11
"r" was used as alias for run and reference command. The solution was
use "f" for the reference command.

Error:
```
root@5d2dda135e50:/fluster# python ./fluster.py
Traceback (most recent call last):
  File "/fluster/./fluster.py", line 25, in <module>
    main = Main()
           ^^^^^^
  File "/fluster/fluster/main.py", line 44, in __init__
    self.parser = self._create_parser()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/fluster/fluster/main.py", line 115, in _create_parser
    self._add_reference_cmd(subparsers)
  File "/fluster/fluster/main.py", line 244, in _add_reference_cmd
    subparser = subparsers.add_parser(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/argparse.py", line 1188, in add_parser
    raise ArgumentError(
argparse.ArgumentError: argument {list,l,run,r,download,d}: conflicting subparser alias: r
```

Fix issue #120 reported by @ceyusa. Moitas grazas.